"""Initial Migration

Revision ID: 95113359a8a3
Revises: 824c460a33a7
Create Date: 2021-06-24 12:54:37.669086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95113359a8a3'
down_revision = '824c460a33a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('cartitems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cartitems_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cartitems_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
